name: Deploy to WordPress

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Prepare Directories and SCSS Compilation
        run: |
          # cssディレクトリの作成と空ファイル作成
          mkdir -p css
          touch css/style.css  # 空のCSSファイルを作成
          
          # SCSSコンパイル
          npm install -g sass
          sass scss/:css/ --style compressed || echo "SCSS compilation had warnings, but continuing..."
          
          # ディレクトリとファイルを確認
          echo "Current directory structure:"
          find . -type d | sort
          
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdegital/
          # 以下の間違ったパラメータを削除
          # mkdir: true
          # logging: standard
          dangerous-clean-slate: false  # 既存ファイルを削除しない
          log-level: verbose  # より詳細なログを出力（loggingからlog-levelに修正）
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
          state-name: ../.ftp-deploy-sync-state.json
          timeout: 60000