name: Deploy to WordPress

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: SCSS Compilation
        run: |
          npm install -g sass
          mkdir -p css
          touch css/style.css
          sass scss/:css/ --style compressed || echo "SCSS compilation warnings, continuing..."
      
      - name: Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp
      
      - name: Debug Server Connection
        run: |
          echo "Testing connection to FTP server..."
          lftp -c "
          open ${{ secrets.FTP_SERVER }};
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }};
          pwd;
          ls -la;
          "
      
      - name: Create Directory Structure
        run: |
          echo "Creating directory structure..."
          lftp -c "
          open ${{ secrets.FTP_SERVER }};
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }};
          set ssl:verify-certificate no;
          set ftp:ssl-allow no;
          mkdir -p public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital;
          mkdir -p public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/css;
          mkdir -p public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/images;
          mkdir -p public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/scss;
          mkdir -p public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/template-parts;
          ls -la public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital;
          "
      
      - name: Upload Files
        run: |
          echo "Uploading files..."
          lftp -c "
          open ${{ secrets.FTP_SERVER }};
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }};
          set ssl:verify-certificate no;
          set ftp:ssl-allow no;
          set ftp:list-options -a;
          lcd $GITHUB_WORKSPACE;
          cd public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital;
          mirror --reverse --verbose --exclude .git/ --exclude .github/ --exclude node_modules/ --exclude deploy.yml --exclude README.md ./;
          ls -la;
          "