name: Deploy to WordPress

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: SCSS Compilation
        run: |
          npm install -g sass
          mkdir -p css
          sass scss/:css/ --style compressed || echo "Continuing despite SCSS warnings"
      
      - name: WordPress Theme Deploy
        run: |
          sudo apt-get update && sudo apt-get install -y lftp
          lftp -c "
          open ${{ secrets.FTP_SERVER }};
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }};
          set ssl:verify-certificate no;
          set ftp:ssl-allow no;
          
          # 必要なディレクトリ構造を確保
          cd /home/r9157144/public_html/;
          mkdir -p testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/css;
          mkdir -p testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/scss;
          mkdir -p testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/images;
          mkdir -p testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/template-parts;
          
          # ファイルのアップロード
          lcd $GITHUB_WORKSPACE;
          cd /home/r9157144/public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital;
          mirror --reverse --exclude .git/ --exclude .github/ --exclude node_modules/ --exclude deploy.yml --exclude README.md ./;
          "