name: Deploy to WordPress

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: SCSS Compilation
        run: |
          npm install -g sass
          mkdir -p css
          touch css/style.css
          sass scss/:css/ --style compressed || echo "SCSS compilation warnings, continuing..."
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          # 以下のパスバリエーションを1つずつ試してください
          # server-dir: public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/
          # または
          server-dir: ./public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/
          # または
          # server-dir: ~/public_html/testservermizuki.onamaeweb.jp/test51274.com/wp-content/themes/nextdigital/
          dangerous-clean-slate: false
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**